language: d

before_install:
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ vivid main universe' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -y update
  
install:
  - sudo apt-get -y install -t vivid libscrypt0 libscrypt-dev libssl1.0.0 libsqlite3-0 libsqlite3-dev libminiupnpc10 libminiupnpc-dev
  - dub fetch doveralls && dub build doveralls

script:
  - dub test --build=unittest-cov --debug=PoWt

after_success:
    ~/.dub/packages/doveralls-*/doveralls
