language: d

d: dmd-2.066.1

before_install:
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ trusty universe' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -y update
  
install:
  - sudo apt-get -y install -t trusty libscrypt0 libscrypt-dev libsqlite3-0 libsqlite3-dev
  
script:
  - dub test --debug=PoWt
