language: d

addons:
  apt:
    sources:
      - debian-sid

    packages:
      - libssl1.0.0
      - libsqlite3-0
      - libsqlite3-dev
      - libscrypt0
      - libscrypt-dev
      - libminiupnpc10
      - libminiupnpc-dev

install:
  - dub fetch doveralls

script:
  - dub test --coverage --combined --debug=PoWt

after_success:
  - dub run doveralls
