language: d

install:
  # dmd
  # dub
  - DMD_VER=2.066.1
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.22
  - DUB=dub-${DUB_VER}-linux-x86_64
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ trusty universe' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -y update
  - sudo apt-get -y install libscrypt-dev libsqlite3-dev
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz
  
script:
  # unittest version with PoW calculation test run
  - dub test --debug=PoWt
