language: d

d: dmd-2.066.1

before_install:
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ vivid main universe' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -y update
  
install:
  - sudo apt-get -y install -t vivid libscrypt0 libscrypt-dev libssl1.0.0 libsqlite3-0 libsqlite3-dev
  
script:
  - dpkg -l|grep libssl1.0.0
  - dub test --debug=PoWt
