language: d

sudo: false

addons:
  apt:
    sources:
      - debian-sid

    packages:
      - libssl1.0.0
      - libsqlite3-0
      - libsqlite3-dev
      - libscrypt0
      - libscrypt-dev
      - libminiupnpc10
      - libminiupnpc-dev

install:
  - git clone --depth=1 --recursive https://github.com/Hackerpilot/Dscanner.git ~/Dscanner
  - if [ ${DC} = "dmd" ]; then make -C ~/Dscanner; fi
  - dub fetch doveralls

cache:
  directories:
    - ~/Dscanner
    - ~/.dub/packages/doveralls-*

script:
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -s --config=.dscanner.ini; fi
  - if [ ${DC} = "dmd" ]; then ~/Dscanner/bin/dscanner -S --config=.dscanner.ini; fi
  - dub test --coverage --combined --debug=PoWt

after_success:
  - dub run doveralls
